//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinesslmsHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinesslmsHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextResources.BusinesslmsHome", typeof(BusinesslmsHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Us.
        /// </summary>
        public static string FacebookButtton {
            get {
                return ResourceManager.GetString("FacebookButtton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowusButton {
            get {
                return ResourceManager.GetString("FollowusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN TO BE AN INDEPENDENT BUSINESS OWNER.
        /// </summary>
        public static string HeatherTitle {
            get {
                return ResourceManager.GetString("HeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach people what a compensation plan is, which different companies use what  compensation plan and break down ours..
        /// </summary>
        public static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are under Construction.
        /// </summary>
        public static string NewsSubtitle {
            get {
                return ResourceManager.GetString("NewsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be tuned to the updates, get in constantly, register and be sure to leave feedback..
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach the basics, principles and values to develop an organization..
        /// </summary>
        public static string PurposeText {
            get {
                return ResourceManager.GetString("PurposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURPOSE.
        /// </summary>
        public static string PurposeTitle {
            get {
                return ResourceManager.GetString("PurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Us in....
        /// </summary>
        public static string RedSocial {
            get {
                return ResourceManager.GetString("RedSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBO Number.
        /// </summary>
        public static string RegisterIboNumber {
            get {
                return ResourceManager.GetString("RegisterIboNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string RegisterPhone {
            get {
                return ResourceManager.GetString("RegisterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who told you about us?.
        /// </summary>
        public static string RegisterQuestion {
            get {
                return ResourceManager.GetString("RegisterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us Here....
        /// </summary>
        public static string RegisterSubtitle {
            get {
                return ResourceManager.GetString("RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to have a debt free and full of time life?....
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string RightsText {
            get {
                return ResourceManager.GetString("RightsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information contained in this single video is intended to awaken your curiosity, capture your interest and give you information with real data. We can’t convince you, but we can give you information so that you become student, and therefore a professional in one of the industries with the greatest potential in this era and in the whole world..
        /// </summary>
        public static string VideoText1 {
            get {
                return ResourceManager.GetString("VideoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network marketing industry has been around for over 100 years. And at the same time, technology has been evolving entrepreneur&apos;s lives. I say entrepreneurs because network marketing is so noble that it doesn&apos;t matter if you have a profession or not, what matters is that you understand it, start it and finish it, thus getting the result you want..
        /// </summary>
        public static string VideoText2 {
            get {
                return ResourceManager.GetString("VideoText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network marketing industry has been around for over one hundred years. However, even the best network marketing companies have their own system and their own compensation plan. The largest companies and most successful distributors are those who live under their principles and values, and that continue to grow, because the world&apos;s largest businesses are being honored..
        /// </summary>
        public static string VideoText3 {
            get {
                return ResourceManager.GetString("VideoText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What The Numbers Mean.
        /// </summary>
        public static string VideoTitle1 {
            get {
                return ResourceManager.GetString("VideoTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amway Oportunity.
        /// </summary>
        public static string VideoTitle2 {
            get {
                return ResourceManager.GetString("VideoTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principles of Our Founders.
        /// </summary>
        public static string VideoTitle3 {
            get {
                return ResourceManager.GetString("VideoTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show what the network marketing industry is and what the best companies are..
        /// </summary>
        public static string VisionText {
            get {
                return ResourceManager.GetString("VisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISION.
        /// </summary>
        public static string VisionTitle {
            get {
                return ResourceManager.GetString("VisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Us.
        /// </summary>
        public static string YoutubeButton {
            get {
                return ResourceManager.GetString("YoutubeButton", resourceCulture);
            }
        }
    }
}
