//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinesslmsHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinesslmsHome() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextResources.BusinesslmsHome", typeof(BusinesslmsHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEARN TO BE AN INDEPENDENT BUSINESS OWNER.
        /// </summary>
        public static string HeatherTitle {
            get {
                return ResourceManager.GetString("HeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our mission is to know that is a compensation plan and which use the best companies..
        /// </summary>
        public static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MISSION.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are under Construction.
        /// </summary>
        public static string NewsSubtitle {
            get {
                return ResourceManager.GetString("NewsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please be tuned to the updates, get in constantly, register and be sure to leave feedback..
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latest News.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our purpose is to learn, do and teach the basic principles and values ​​to develop an organization..
        /// </summary>
        public static string PurposeText {
            get {
                return ResourceManager.GetString("PurposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PURPOSE.
        /// </summary>
        public static string PurposeTitle {
            get {
                return ResourceManager.GetString("PurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find Us in....
        /// </summary>
        public static string RedSocial {
            get {
                return ResourceManager.GetString("RedSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join us Here....
        /// </summary>
        public static string RegisterSubtitle {
            get {
                return ResourceManager.GetString("RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready to have a debt free and full of time life?....
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What The Numbers Mean.
        /// </summary>
        public static string VideoTitle1 {
            get {
                return ResourceManager.GetString("VideoTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Amway Oportunity.
        /// </summary>
        public static string VideoTitle2 {
            get {
                return ResourceManager.GetString("VideoTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principles of Our Founders.
        /// </summary>
        public static string VideoTitle3 {
            get {
                return ResourceManager.GetString("VideoTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our vision is to know the network marketing industry and what are the best companies..
        /// </summary>
        public static string VisionText {
            get {
                return ResourceManager.GetString("VisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VISION.
        /// </summary>
        public static string VisionTitle {
            get {
                return ResourceManager.GetString("VisionTitle", resourceCulture);
            }
        }
    }
}
