//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinesslmsHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinesslmsHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextResources.BusinesslmsHome", typeof(BusinesslmsHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN TO BE AN INDEPENDENT BUSINESS OWNER.
        /// </summary>
        public static string HeatherTitle {
            get {
                return ResourceManager.GetString("HeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra misión es saber que es un plan de compensación y cuales usan las mejores compañías..
        /// </summary>
        public static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro propósito es aprender, hacer y enseñar los básicos principios y valores para desarrollar una organización..
        /// </summary>
        public static string PurposeText {
            get {
                return ResourceManager.GetString("PurposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURPOSE.
        /// </summary>
        public static string PurposeTitle {
            get {
                return ResourceManager.GetString("PurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra visión es conocer la industria del mercado en red y cuáles son las mejores compañías..
        /// </summary>
        public static string VisionText {
            get {
                return ResourceManager.GetString("VisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISION.
        /// </summary>
        public static string VisionTitle {
            get {
                return ResourceManager.GetString("VisionTitle", resourceCulture);
            }
        }
    }
}
